config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lists
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates_presence_of :title, :date, :note

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, :only => [:show, :edit, :update, :destroy]

  def index 
    @lists = List.all
  end

  def new 
    @list = List.new
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to list_path(@list), notice: "新增成功"
    else
      render :edit
    end
  end

  def destroy
    if @list.date > Date.today
      @list.destroy

      redirect_to lists_url
    else
      redirect_to lists_url, :notice => "超過時間，無法刪除"
    end
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_url
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title, :date, :note)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<% if @list.errors.present? %>
  <ul>
    <% @list.errors.each do |error, message| %>
      <li>
        <%= "#{error.capitalize} #{message}" %>
      </li>
    <% end %>
  </ul>
<% end %>
<div class="form container">
  <%= form_for (list) do |f| %>
    <div class="form-group">
      <%= f.label :title, "Name" %>
      <%= f.text_field :title %><br />
    </div>

    <div class="form-group">
      <%= f.label :date, "Date" %>
      <%= f.text_field :date %><br />
    </div>

    <div class="form-group">
      <%= f.label :note, "Note" %>
      <%= f.text_area :note %><br />
    </div>

    <%= f.submit %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<h1>編輯事項</h1>

<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div class="jumbotron text-center">
  <h1> To do list </h1>
</div>

<table class="table table-striped table-condensed">
  <% @lists.each do |list| %>
    <tr>
      <td><%= list.title %></td>
      <td><%= link_to "show", list_path(list) %></td>
      <td><%= link_to "edit", edit_list_path(list) %></td>
      <td><%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, list_path(list), method: :delete, data:{ confirm: "Are you sure?" } %></td>
  <% end %>
</table>

<button type="button" class="btn btn-default btn-sm">
  <%= link_to "New item", new_list_path %> 
</button>

app/views/lists/new.html.erb
<h1>新增事項</h1>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="wrapper">
  <h2 class="title"><%= @list.title %></h2><br />
  <p><%= @list.date %></p><br />
  <p><%= simple_format(@list.note) %></p>
</div>

<button type="button" class="btn btn-default btn-sm">  
  <%= link_to "Back", lists_path %>
</button>